AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Secrets creation for pipeline creation.

Parameters:
  githubtoken:
    Description: token for GitHub Access
    Type: String
    NoEcho: "true"
    MinLength: "1"

Resources:
  GithubConnParams:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Github Connection Parameters.
      Name: GithubTokenConnParams
      SecretString: !Sub |
        {
          "GithubPullToken": "${githubtoken}"
        }